title: Path2Destiny
description: Guidance to help you write your own story.
url: "https://soullifter.github.io"
baseurl: ""
theme: minima

author:
  Yashwanth Adunukota
  yashulakshya310@gmail.com

# Header navigation (Minima uses this, not `nav`)
header_pages:
  - index.markdown      # Home (optional; remove to hide)
  - about.markdown      # My Story
  - buckets.md          # Five Buckets (optional)
  - packages.md         # Packages
  - subscribe.md        # Subscribe
  - faq.md              # FAQ
  - contact.md          # Contact

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
