title: Path2Destiny
description: Coaching & mentorship to help you write your own story.
url: "https://soullifter.github.io"   # your user site
baseurl: ""                           # user site = empty
theme: minima

author:
  name: Yashwanth Adunukota
  email: yashulakshya310@gmail.com

# Header navigation
nav:
  - title: "About"
    url: /about/
  - title: "Packages"
    url: /packages/
  - title: "Subscribe"
    url: /subscribe/
  - title: "FAQ"
    url: /faq/
  - title: "Contact"
    url: /contact/

# Build
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO (optional)
social_links:
  - { platform: instagram, user_url: "https://instagram.com/TheUnshakableEmpire" }
